version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: discordfeed-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: discordfeed_user
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: discordfeed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U discordfeed_user -d discordfeed"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0
    container_name: discordfeed-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
